### PR TITLE
"Fix" bot-spy launcher script

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Rewrite bot-spy launcher script to add its own class paths, then hand off to the updated (lcm-proj/lcm#143) lcm-spy that sets up the necessary class paths for LCM itself.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/libbot2/2)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@wxmerkt, PTAL; thanks!

**Comment by wxmerkt** [comment]
@mwoehlke-kitware Apologies for the delay - hope you had happy holidays. Thanks for fixing this, this looks good to me (I tested a similar quick fix locally). Perhaps there should be a ``CHANGELOG.md`` indicating that as off this PR the minimum required LCM version is ``1.3.95`` (https://github.com/lcm-proj/lcm/pull/151) and that versions prior to this PR require ``v1.3-lts``.

**Comment by david-german-tri** [comment]
+@david-german-tri platform

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/libbot2/2#-:-K_fFLwbLFwvwmbNC7dK:bmrx3ks)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/libbot2/2#-:-K_fFvo3erY7w2SJd-ID:bnfp4nl)*

**Pull request merged**
