### PR TITLE
Add Jammy provisioning; use latest LCM to address PY_SSIZE_T_CLEAN error

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
FYI @sammy-tri - stole yer changes, hacking in stuff for testing in Anzu

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/libbot2/22)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sammy-tri Can I ask for your review?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-:-NH-QZdT9INRRHnvE5Qn:b-vvq0k0)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri, platform LGTM missing (waiting on @EricCousineau-TRI and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH-QVsE3XicHPRvV-Wl:-NH-QVsE3XicHPRvV-Wm:b3xgxpo) (no related file):*
Working: Should restore other platforms if we decide on good commit / versioning, and reflect the changes there.

___

**Review by sammy-tri — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/libbot2/22)* status: 4 unresolved discussions, LGTM missing from assignee sammy-tri, platform LGTM missing (waiting on @EricCousineau-TRI)

___
*[`.github/CODE_OF_CONDUCT.md` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH0-svp3e9ELuPjiqeK:-NH0-svp3e9ELuPjiqeL:bx98spg) ([raw file](https://github.com/robotlocomotion/libbot2/blob/dd8d4d4d3beeb6f9ce723342c553808b97e2266e/.github/CODE_OF_CONDUCT.md#L1)):*
> ```Markdown
> # Contributor Covenant Code of Conduct
> ```

was the stuff in `.github` not supposed to be there originally?
___
*[`scripts/package/linux/ubuntu/bionic/package` line 0 at r2](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH0-4ZMBhsYWlITwY8g:-NH0-4ZMBhsYWlITwY8h:b-awc37f) ([raw file](https://github.com/robotlocomotion/libbot2/blob/5144f2c0e59da9e305e5c4148a45213288d2d464/scripts/package/linux/ubuntu/bionic/package#L0)):*
If we're deleting the `package` script, should we also delete the stuff in `scripts/setup` for the related distros?
___
*[`scripts/package/linux/ubuntu/focal/package` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH-zTBe-d-6dKDg_zCy:-NH-zTBe-d-6dKDg_zCz:b-bdn7nz) ([raw file](https://github.com/robotlocomotion/libbot2/blob/dd8d4d4d3beeb6f9ce723342c553808b97e2266e/scripts/package/linux/ubuntu/focal/package#L1)):*
> ```
> #!/bin/bash
> ```

I can maybe see deleting the bionic version, but  why focal?

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/libbot2/22)* status: 4 unresolved discussions, LGTM missing from assignee sammy-tri, platform LGTM missing (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH-QVsE3XicHPRvV-Wl:-NH004CQ6EvOVj6KdVqY:briq2cm) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should restore other platforms if we decide on good commit / versioning, and reflect the changes there.
</blockquote></details>

(oh, missed this comment and asked for an explanation inline.  reply wherever)

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/libbot2/22)* status: 4 unresolved discussions, LGTM missing from assignee sammy-tri, platform LGTM missing (waiting on @EricCousineau-TRI and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH-QVsE3XicHPRvV-Wl:-NH2Oi7o6F1K2EPhFav7:b-hf4gcf) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

(oh, missed this comment and asked for an explanation inline.  reply wherever)
</blockquote></details>

No worries.
But to confirm, can I ask if you're good with the `jammy` changes I applied on top of yours?

If so, will (try to) restore and reflect changes on all platforms, in which case inline discussions become moot-ified.

___
___
*[`.github/CODE_OF_CONDUCT.md` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH0-svp3e9ELuPjiqeK:-NH2OnvN-0qCf_PeWVP5:b-ojel1o) ([raw file](https://github.com/robotlocomotion/libbot2/blob/dd8d4d4d3beeb6f9ce723342c553808b97e2266e/.github/CODE_OF_CONDUCT.md#L1)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

was the stuff in `.github` not supposed to be there originally?
</blockquote></details>

Point may be moot given above discussion.
___
*[`scripts/package/linux/ubuntu/bionic/package` line  at r2](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH0-4ZMBhsYWlITwY8g:-NH2Op-55GxrT99IGDYh:b-ojel1o) ([raw file](https://github.com/robotlocomotion/libbot2/blob/5144f2c0e59da9e305e5c4148a45213288d2d464/scripts/package/linux/ubuntu/bionic/package#L)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

If we're deleting the `package` script, should we also delete the stuff in `scripts/setup` for the related distros?
</blockquote></details>

Point may be moot given above discussion.
___
*[`scripts/package/linux/ubuntu/focal/package` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH-zTBe-d-6dKDg_zCy:-NH2OpDO3N_hgEjOc1Lq:b-ojel1o) ([raw file](https://github.com/robotlocomotion/libbot2/blob/dd8d4d4d3beeb6f9ce723342c553808b97e2266e/scripts/package/linux/ubuntu/focal/package#L1)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I can maybe see deleting the bionic version, but  why focal?
</blockquote></details>

Point may be moot given above discussion.

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/libbot2/22)* status: 4 unresolved discussions, LGTM missing from assignee sammy-tri, platform LGTM missing (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH-QVsE3XicHPRvV-Wl:-NH5dfHt0n76ANrhNirq:b-d5b2yh) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

No worries.
But to confirm, can I ask if you're good with the `jammy` changes I applied on top of yours?

If so, will (try to) restore and reflect changes on all platforms, in which case inline discussions become moot-ified.
</blockquote></details>

The LCM version change was the only one I noticed, and that's OK with me.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/libbot2/22)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri, platform LGTM missing (waiting on @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH-QVsE3XicHPRvV-Wl:-NH6-Rly8rEO_quwT4WF:b-896fix) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The LCM version change was the only one I noticed, and that's OK with me.
</blockquote></details>

Done.

___

**Comment by EricCousineau-TRI** [comment]
Ergh blarg. Will try a few more times to appease CI, or may just leave it as "meh".

**Review by sammy-tri — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/libbot2/22)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri, platform LGTM missing (waiting on @EricCousineau-TRI)

___
*[`.github/workflows/ci.yml` line 83 at r4](https://reviewable.io/reviews/robotlocomotion/libbot2/22#-NH6PudqCMY3a7xtaREi:-NH6PudqCMY3a7xtaREj:bfzhs0t) ([raw file](https://github.com/robotlocomotion/libbot2/blob/84adbcdd8c2deb8c09647af16c4cc8aaf19610e2/.github/workflows/ci.yml#L83)):*
> ```YAML
>       - name: Build
>         run: |
>           ./scripts/package/linux/ubuntu/common/build.sh
> ```

Looking at the CI error, I think `build.sh` needs at least one argument, even if it's just `""` (empty string)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/libbot2/22)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri, platform LGTM missing (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Nuts, now Mac is finicky.

**Comment by jwnimmer-tri** [comment]
If you like, I think you could delete mac stuff from the ci yaml entirely, and nobody would complain?

**Comment by EricCousineau-TRI** [comment]
Works for me!

**Comment by EricCousineau-TRI** [comment]
Gonna go ahead and merge onwards!

**Pull request merged**
